export const MEDICINES_LOADING = 'MEDICINES_LOADING';
export const MEDICINES_FAILED = 'MEDICINES_FAILED';
export const ADD_MEDICINES = 'ADD_MEDICINES';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';
export const ADD_COMMENTS = 'ADD_COMMENTS';